version: '3.1'
services:
  web:
    image: odoo:17.0
    depends_on:
      - odoo17projectdata
    ports:
      - "8017:8069"
    volumes:
      - D:/Odoo/odoo-17.0:/var/lib/odoo
      - ./debian:/etc/odoo
      - ./addons:/mnt/addons
      - ./addons-custom:/mnt/addons-custom
    environment:
      - HOST=odoo17projectdata
      - USER=odoo17
      - PASSWORD=123456
  odoo17projectdata:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
