
from . import province
from . import district
from . import ward
from . import sim_maker
from . import bank_account
from . import installment_period
from . import prepay_amount
from . import sim_maker_discount
from . import sim_maker_installment
from . import sim_maker_support
from . import sim_maker_rating
from . import res_config_settings
from . import telecom_supplier
from . import mobile_package
from . import package_endown
from . import sim_category
from . import sim_data
from . import sim_warehouse
from . import comment_history
from . import sim_upload_history
from . import sim_upload_history_line
from . import res_company
from . import kafka_consumer
from . import res_users
from . import configuration_satellite_web